# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html

# conda activate snakemake
# snakemake -n (dry run)
# snakemake --use-conda --cores 60 -k -p

import os
import pandas as pd

configfile: "config/config.yaml"

samples = pd.read_table(config["samples"])
#nkis = pd.read_table(config["nkis"])
#carryover = pd.read_table(config["carryovers"])

sample_ids = samples["samples"].tolist()
#nki_ids = nkis["samples"].tolist()
#carry_ids = carryover["samples"].tolist()

RESULTS_DIR = "results"

rule all:
    input:
        RESULTS_DIR + "/merged/rpkm_long.tsv",
        RESULTS_DIR + "/merged/presence_absence_long.tsv"


##### Modules #####
include: "rules/trimmomatic.smk"
include: "rules/cutadapt.smk"
include: "rules/spades.smk"
include: "rules/mmseqs2.smk"
include: "rules/mmseqs2_tsv.smk"
include: "rules/rename_contigs.smk"
include: "rules/merge_contigs.smk"
include: "rules/merge_taxonomy.smk"
include: "rules/extract_viral_contigs.smk"
include: "rules/blast.smk"
include: "rules/sort_remove_self.smk"
include: "rules/filter_edges.smk"
include: "rules/clustering.smk"
include: "rules/merge_taxonomy_clusters.smk"
include: "rules/dehybridize_clusters.smk"
include: "rules/select_reps.smk"
include: "rules/filter_reps_length.smk"
include: "rules/bbmap_to_reps.smk"
include: "rules/coverm.smk"
include: "rules/calculate_breadth.smk"
include: "rules/merge_read_counts_samples.smk"
#include: "rules/merge_read_counts_controls.smk"
include: "rules/merge_breadth.smk"
#include: "rules/remove_control_reads.smk"
include: "rules/filter_read_counts.smk"
include: "rules/calculate_rpkm.smk"


